// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3UluJ84MhC7ZKjyMn2wlVUG7PhRMLdE',
    appId: '1:830373956277:web:d50e2e9d8cf46c90938cfc',
    messagingSenderId: '830373956277',
    projectId: 'tt9-logain-chat-app',
    authDomain: 'tt9-logain-chat-app.firebaseapp.com',
    storageBucket: 'tt9-logain-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kkHMJ1RQve27gNxZuovVV_-0SWRmOzc',
    appId: '1:830373956277:android:d1ec64fc7128b38a938cfc',
    messagingSenderId: '830373956277',
    projectId: 'tt9-logain-chat-app',
    storageBucket: 'tt9-logain-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkH7BKJDtcOsTw7EtHwyqzUHw5NpU5rc',
    appId: '1:830373956277:ios:1764bec740de995c938cfc',
    messagingSenderId: '830373956277',
    projectId: 'tt9-logain-chat-app',
    storageBucket: 'tt9-logain-chat-app.firebasestorage.app',
    androidClientId: '830373956277-ciubrlnp2p6i71ti5giiutpauvjsakre.apps.googleusercontent.com',
    iosClientId: '830373956277-u5dsbkffpujfhc13n31ionrobifv5ust.apps.googleusercontent.com',
    iosBundleId: 'com.example.madrassti',
  );
}
